config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :update, :edit, :index] do
    member do
      get 'notifications'
      get 'refresh'
    end
    resources :friendships, :only => [:index, :create, :update, :destroy] do
      collection do
        get 'search_friends'
        get 'search'
        get 'pendings'
        post 'invite'
      end
    end
    resources :bets, :only => [:create, :new, :index]
    resources :bet_participations, :only => [:update, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :bets, :only => [:show, :edit, :update] do
    resources :comments, only: [:create, :new, :show]
    get 'community', on: :collection
    get 'pending', on: :collection
    get 'inplay', on: :collection
    get 'completed', on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  root :to => 'users#index'
end

app/models/user.rb
require 'open-uri'

class User < ActiveRecord::Base
  include PgSearch

  attr_accessible :username, :password, :first_name, :last_name, :profile_pic, :provider, :uid
  attr_reader :password

  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token
  #before_save :set_default_pic

  pg_search_scope :search_by_name_and_email, against: [:first_name, :last_name, :username], :using => {:tsearch => {:prefix => true}}

  has_attached_file :profile_pic, :styles => {
    :large => "600x600#",
    :medium => "250x250#",
    :small => "50x50#",
    :thumb => "30x30#"},
    :default_url => ":style/missing.png"

  has_many(
  :outbound_friendships,
  class_name: "Friendship",
  foreign_key: :out_friend_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :inbound_friendships,
  class_name: "Friendship",
  foreign_key: :in_friend_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :friends, through: :outbound_friendships, source: :in_friend, :conditions => ['Friendships.pending_flag = ?', false]
  has_many :outbound_pending_friends, through: :outbound_friendships, source: :in_friend, :conditions => ['Friendships.pending_flag = ?', true]
  has_many :inbound_pending_friends, through: :inbound_friendships, source: :out_friend, :conditions => ['Friendships.pending_flag = ?', true]


  has_many(
  :authored_bets,
  class_name: "Bet",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :bet_participations,
  class_name: "BetParticipation",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :bets, through: :bet_participations, source: :bet
  has_many :inplay_bets, through: :bet_participations, source: :bet, :conditions => ['bets.status = ?', 'in play']
  has_many :inbound_pending_bets, through: :bet_participations, source: :bet, :conditions => ['bet_participations.status = ? AND bets.status = ?', 'pending', 'pending']
  has_many :community_bets, through: :friends, source: :bets

  has_many(
  :authored_comments,
  class_name: "Comment",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :notifications,
  class_name: "Notification",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :winning_entries,
  class_name: "WinnerEntry",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :losing_entries,
  class_name: "LoserEntry",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :bets_won, :through => :winning_entries, source: :bet
  has_many :bets_lost, :through => :losing_entries, source: :bet

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    #this line was inserted to account for users that login via 3rd party FB/Twitter accts, for which they dont' have a yibs pw
    return false if !self.password_digest
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def find_friendship(friend)
    Friendship.find_by_out_friend_id_and_in_friend_id(self.id, friend.id)
  end

  def find_bet_participation(bet)
    BetParticipation.find_by_user_id_and_bet_id(self.id, bet.id)
  end

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def abbrev_name
    return "#{self.first_name} #{self.last_name[0] if self.last_name}"
  end

  def community_bets
  @bets = self.bets
    self.friends.each do |friend|
      @bets = (@bets + friend.bets.where( private: false ) ).uniq
    end
    @bets.sort_by { |bet| Time.now()-bet.updated_at }
  end

  def pending_bets
    @bets = self.bets.where( status: 'pending' )
    @bets.sort_by { |bet| Time.now()-bet.updated_at }
  end

  def inplay_bets
    @bets = self.bets.where( status: 'in play' )
    @bets.sort_by { |bet| Time.now()-bet.updated_at }
  end

  def completed_bets
    @bets = self.bets.where( status: 'completed' )
    @bets.sort_by { |bet| Time.now()-bet.updated_at }
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def set_default_pic
    if !self.profile_pic.present?
      self.profile_pic = open("http://www.tenniswood.co.uk/wp-content/uploads/2010/01/design-fetish-no-photo-facebook-1.jpg")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show, :edit, :update, :index]
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_admin_access!, :only => [:edit, :update]

  def create
    @user = User.find_by_username(params[:user][:username])
    if @user && !@user.password_digest && !@user.provider
      if @user.update_attributes(params[:user])
        self.current_user = @user
        redirect_to root_url
      else
        render :json => @user.errors.full_messages
      end
    else
      @user = User.new(params[:user])
      if @user.save
        self.current_user = @user
        redirect_to root_url
      else
        render :json => @user.errors.full_messages
      end
    end
  end

  def new
    @user = User.new
  end

  def show
    puts "HEERRRRRRRRRRRRRRRRRRRRRRRRRREE"
    @user = User.find(params[:id])
    if @user == current_user
      @bets = @user.bets
    else
      @bets = (@user.bets.where(private: false) + @user.bets.select { |bet| bet.participants.include?(current_user) }).uniq
    end
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)
    if request.xhr?
      puts "request.xhr success"
      render partial: 'users/show_details_lightbox', locals: {user: @user, bets: @bets}
    else
            puts "request.xhr failed"
      render partial: 'users/show_details_lightbox', locals: {user: @user, bets: @bets}
    end
  end

  def edit
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def update
    if current_user.id == params[:id].to_i
      @user = current_user
      @user.update_attributes(params[:user])
      if @user.save
        redirect_to root_url
      else
        render :json => @user.errors.full_messages
      end
    else
      redirect_to edit_user_url(current_user)
    end
  end

  def index
    @user = current_user
    @bet = Bet.new
    @bets = @user.community_bets
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)
    @notifications = @user.notifications
    # @community_bets = @user.community_bets
    # @pending_bets = @user.pending_bets
    # @inplay_bets = @user.inplay_bets
    # @completed_bets = @user.completed_bets
    @user_bet_count = @user.bets.count
    @user_inplay_count = @user.inplay_bets.count
    @user_win_count = @user.bets_won.count
  end

  def notifications
    @user = current_user
    @notifications = @user.notifications
    render :notifications
  end

  def refresh
    #can be optimized to utilize only 1 or 2 passes into the database rather than 4-5
    @user = current_user
    @notifications = @user.notifications
    @community_bets = @user.community_bets
    @pending_bets = @user.pending_bets
    @inplay_bets = @user.in_play_bets
    @completed_bets = @user.completed_bets
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_lightbox.html.erb
<div class="user-edit-form light-box-form hidden" id="user-edit-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">Edit User</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group">
    <%= render "form", :user => @user %>
  </div>
</div>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" enctype="multipart/form-data" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_first_name">First Name</label>
  <input
    id="user_first_name"
    name="user[first_name]"
    value="<%= user.first_name %>"
    type="text">
  <br>

  <label for="user_last_name">Last Name</label>
  <input
    id="user_last_name"
    name="user[last_name]"
    value="<%= user.last_name %>"
    type="text">
  <br>

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     value="<%= user.username %>"
     type="text">
  <br>

  <% unless user.persisted? %>
  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
	 <% end %>
  <br>
  <br>
  Current Profile Picture:<br>
  <% if user.profile_pic.present? %>
    <%= image_tag user.profile_pic.url(:small) %><br>
  <% end %>
  <label for="user_profile_pic">Upload New Picture</label><br>
  <input type="file" id="user_profile_pic" name="user[profile_pic]">
  <br>
  <br>
  <input type="submit" value="<%= message %>">
</form>

app/views/users/_notifications.html.erb
<% if !notifications || notifications.empty? %>
  <li><%= "No Notifications" %></li>
<% else %>
  <% notifications.each do |notification| %>
  	<li class="notifications-link">
  		<a href="<%= notification.link %>" data-remote="true"><%= notification.text %></a>
  	</li>
    <% end %>
<% end %>

app/views/users/_show_details_lightbox.html.erb
<section class="user-details">
  <div class="user-show-pic"><%= image_tag user.profile_pic.url(:medium) %></div>
<ul class="user-details">
	<li>Username: <%= user.username %></li>
	<li>Name: <%= user.first_name %> <%= user.last_name %></li>
	<li>Total Bets: <%= user.bets.count %></li>
</ul>
</section>
<% if user.friends.include?(current_user) %>
<div class="bets">
  <header class="group">

    <% if !bets || bets.empty? %>
    <div class="no-bets">User has No Bets</div>
    <% else %>
    <ul class="bets-list" id="user-show-bets-feed">
      <%= render "bets/display_bets" %>
    </ul>
    <% end %>

  </header>
</div>
<% end %>

app/views/users/_show_lightbox.html.erb
<div class="user-show-form light-box-form hidden" id="user-show-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">User Show Page</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group" id="user-show-content">
  </div>
</div>

app/views/users/_user_dashboard.html.erb
<section class="user_dashboard group">
  <%= image_tag user.profile_pic.url(:small), :id => "profile_pic" %>
  <div class="profile">
    <span id="name"><%= user.abbrev_name %>.</span>
    <a href="<%= edit_user_url(user) %>" id="name_support">modify profile</a>
    <%= button_to "Add Bet", new_user_bet_url(user), method: 'get' %>
    <%= button_to "Update Friends", user_friendships_url(user), method: 'get' %>
  </div>
</section>

app/views/users/find_friends.html.erb
<ul>
  <% @users.each do |user| %>
    <%=  %>
</ul>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html copy.erb
<section class="user-details">
  <%= image_tag @user.profile_pic.url(:small) %>
  <ul class="user-details">
  	<li>Username: <%= @user.username %></li>
  	<li>Name: <%= @user.first_name %> <%= @user.last_name %></li>
  	<li>Total Bets: <%= @user.bets.count %></li>
  </ul>
</section>
<% if @user.friends.include?(current_user) %>
<section class="user_bets">
		<p>
		  <%= render "/bets/display_bets", :bets => @bets %>
		</p>
</section>
<% end %>